### ISSUE TITLE
arrow.parser.ParserMatchError: Failed to match 'YYYY-MM-DDTHH:mm:ss' when parsing '2025-01-20T16:47:08+01:00'.

### ISSUE THREAD

**Issue by games-geeks** [Linus2punkt0/bluesky-crossposter#78]
Hello, 

i'm using bluesky-crossposter with docker.
It seems to be ok when i post on blusky.

But i have this error when i use blusky api: [williamsdb](https://github.com/williamsdb)
[php2Bluesky](https://github.com/williamsdb/php2Bluesky)

```shell
2025/01/20 08:59:46,stdout, (<module> crosspost.py:38)

2025/01/20 08:59:46,stdout,arrow.parser.ParserMatchError: Failed to match 'YYYY-MM-DDTHH:mm:ss' when parsing '2025-01-20T16:47:08+01:00'.
2025/01/20 08:59:46,stdout,    raise ParserMatchError(
2025/01/20 08:59:46,stdout,"  File \"/usr/local/lib/python3.12/site-packages/arrow/parser.py\", line 323, in parse
2025/01/20 08:59:46,stdout,         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/20 08:59:46,stdout,    dt = parser.DateTimeParser(locale).parse(
2025/01/20 08:59:46,stdout,"  File \"/usr/local/lib/python3.12/site-packages/arrow/factory.py\", line 292, in get
2025/01/20 08:59:46,stdout,           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/20 08:59:46,stdout,"    return _factory.get(*args, **kwargs)
2025/01/20 08:59:46,stdout,"  File \"/usr/local/lib/python3.12/site-packages/arrow/api.py\", line 91, in get
2025/01/20 08:59:46,stdout,                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/20 08:59:46,stdout,"    created_at = arrow.get(feed_view.post.record.created_at.split(\".\")[0], date_in_format)
2025/01/20 08:59:46,stdout,"  File \"/input/bluesky.py\", line 55, in get_posts
2025/01/20 08:59:46,stdout,                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/20 08:59:46,stdout,"    posts, deleted = get_posts(timelimit, deleted)
2025/01/20 08:59:46,stdout,"  File \"//crosspost.py\", line 18, in run
2025/01/20 08:59:46,stdout,    run()
2025/01/20 08:59:46,stdout,"  File \"//crosspost.py\", line 36, in <module>
2025/01/20 08:59:46,stdout,2025-01-20 16:59:45 [ERROR]: Traceback (most recent call last):
```

In his code, the date format is 
`'createdAt' => date('c')`
Thanks for your help

**Comment by Linus2punkt0** [comment]
Try checking out this branch and running again: https://github.com/Linus2punkt0/bluesky-crossposter/tree/date-format-handling 

It should resolve the issue. If things seem to work I'll merge it to main.

**Comment by games-geeks** [comment]
Hello, 
Thanks, i tried the new branh and i still have the error

```
2025/01/22 09:36:45,stdout, (<module> crosspost.py:38)
2025/01/22 09:36:45,stdout,arrow.parser.ParserMatchError: Failed to match 'YYYY-MM-DDTHH:mm:ss' when parsing '2025-01-22T17:35:39+00:00'.
2025/01/22 09:36:45,stdout,    raise ParserMatchError(
2025/01/22 09:36:45,stdout,"  File \"/usr/local/lib/python3.12/site-packages/arrow/parser.py\", line 323, in parse
2025/01/22 09:36:45,stdout,         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/22 09:36:45,stdout,    dt = parser.DateTimeParser(locale).parse(
2025/01/22 09:36:45,stdout,"  File \"/usr/local/lib/python3.12/site-packages/arrow/factory.py\", line 292, in get
2025/01/22 09:36:45,stdout,           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/22 09:36:45,stdout,"    return _factory.get(*args, **kwargs)
2025/01/22 09:36:45,stdout,"  File \"/usr/local/lib/python3.12/site-packages/arrow/api.py\", line 91, in get
2025/01/22 09:36:45,stdout,                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/22 09:36:45,stdout,"    created_at = arrow.get(feed_view.post.record.created_at.split(\".\")[0], date_in_format)
2025/01/22 09:36:45,stdout,"  File \"/input/bluesky.py\", line 55, in get_posts
2025/01/22 09:36:45,stdout,                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/22 09:36:45,stdout,"    posts, deleted = get_posts(timelimit, deleted)
2025/01/22 09:36:45,stdout,"  File \"//crosspost.py\", line 18, in run
2025/01/22 09:36:45,stdout,    run()
2025/01/22 09:36:45,stdout,"  File \"//crosspost.py\", line 36, in <module>
2025/01/22 09:36:45,stdout,2025-01-22 17:36:45 [ERROR]: Traceback (most recent call last):
```

I change the other program (php)
instead of  'createdAt' => date('c') i wrote  :'createdAt' => date('Y-m-d\TH:i:s.156888\Z') and it's ok

**Comment by Linus2punkt0** [comment]
Hm, it seems from the error that it's still running the old code. But if you solved it another way then maybe it's fine!

**Comment by games-geeks** [comment]
i think i'm on the new branch
 git branch
* date-format-handling
and after i run docker-compose.
i'll try again.
But if you solved it another way then maybe it's fine! => Yes it's fine, but for others projects in php we can have the same trouble

**Comment by Linus2punkt0** [comment]
Did you run git pull after switching? Check if you have the function "get_date()" in bluesky.py.

**Comment by games-geeks** [comment]
So: 
git branch
* date-format-handling
  main

 git pull
Already up to date.

 grep get_date bluesky.py
        created_at = get_date(feed_view.post.record.created_at.split(".")[0])
            created_at = get_date(feed_view.reason.indexed_at.split(".")[0])
def get_date(date_string):

After i deleted my docker image and rebuilt.
But i still have the problem

**Comment by Linus2punkt0** [comment]
Odd, maybe the branch needs to be specified in the image. 

The error points to:
_created_at = arrow.get(feed_view.post.record.created_at.split(\".\")[0], date_in_format)_

Which has been replaced with:
_created_at = get_date(feed_view.post.record.created_at.split(".")[0])_

But I merged it into main now, so try running again with main.

**Comment by games-geeks** [comment]
i will try with another docker instance.
